name = "hunny-17/vault-practice"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Practice Aiken vault validator for CertChain CIP-68 Phase A.4"

[repository]
user = "hunny-17"
project = "vault-practice"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
