name = "hunny-17/certchain-validator"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'hunny-17/certchain-validator'"

[repository]
user = "hunny-17"
project = "certchain-validator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
